export type Language = 'en' | 'sl';

export const translations = {
  'en': {
    appName: 'Dujpp',
    englishLabel: 'English',
    slovenianLabel: 'Slovenian',
    date: 'Date',
    startStation: 'Departure station',
    endStation: 'Arrival station',
    showMap: 'Show map',
    timetable: 'Show timetable',
    confirmLocation: 'Confirm location',
    userLocationError: 'Location access denied.',
    chooseStation: 'Where are you traveling to?',
    dateError: 'Choose a valid date.',
    noStartStation: 'No start station selected.',
    noEndStation: 'No end station selected.',
    sameStationsError: 'Start and end stations cannot be the same.',
    availableFares: 'Available fares',
    invalidParams: 'Search parameters invalid. The page will redirect back to the main page in ',
    seconds: ' seconds',
    selectDateTime: 'Select date and time',
    cancelButton: 'Cancel',
    nextButton: 'Next',
    dateTimeFormat: 'DD.MM.YYYY hh:mm a',
    timeFormat: 'hh:mm a',
    departureTime: 'Departure Time (from)',
    departureTimeTo: 'Departure Time (to)',
    arrivalTime: 'Arrival Time (to)',
    loadingTimetables: 'Searching for timetables...',
    noAvailableFares: 'No available fares found.',
    departure: 'Departure',
    arrival: 'Arrival',
    operatedBy: 'Operated by',
    buyTicket: 'Buy ticket',
    paymentPageTitle: 'Buy Ticket',
    paymentPageDescription: 'You are about to buy a ticket for the selected route. Please proceed with the payment to complete your purchase.',
    travelingElsewhere: 'Traveling elsewhere',
    line: 'Line',
    at: 'at',
    summary: 'Summary of purchase',
    adults: 'Adults',
    children714: 'Children (7-14)',
    children06: 'Children (0-6)',
    baggage: 'Baggage',
    pay: 'Pay',
    totalPrice: 'Total price',
    download: 'Download',
    share: 'Share',
    proceedToPayment: 'Proceed to Payment',
    youAreHere: 'You are here.',
  },
  'sl': {
    appName: 'Dujpp',
    englishLabel: 'Angleški',
    slovenianLabel: 'Slovenski',
    date: 'Datum',
    startStation: 'Vstopna postaja',
    endStation: 'Izstopna postaja',
    showMap: 'Prikaži na zemljevidu',
    timetable: 'Prikaži vozni red',
    confirmLocation: 'Potrdi lokacijo',
    userLocationError: 'Dostop do lokacije uporabnika onemogočen.',
    chooseStation: 'Kam potujete?',
    dateError: 'Izberite veljaven datum.',
    noStartStation: 'Izberite vstopno postajo.',
    noEndStation: 'Izberite izstopno postajo.',
    sameStationsError: 'Vstopna in izstopna postaja ne moreta biti enaki.',
    availableFares: 'Razpoložljivi vozni redi',
    invalidParams: 'Parametri iskanja so neveljavni. Stran bo preusmerjena nazaj na izbiro postaj čez ',
    seconds: 'sekund',
    selectDateTime: 'Izberite datum in čas',
    cancelButton: 'Prekliči',
    nextButton: 'Naprej',
    dateTimeFormat: 'DD.MM.YYYY HH:mm',
    timeFormat: 'HH:mm',
    departureTime: 'Čas odhoda (od)',
    departureTimeTo: 'Čas odhoda (do)',
    arrivalTime: 'Čas prihoda (do)',
    loadingTimetables: 'Iskanje voznih redov ...',
    noAvailableFares: 'Za izbrane postaje ni najdenih voznih redov.',
    departure: 'Odhod',
    arrival: 'Prihod',
    operatedBy: 'Podjetje',
    buyTicket: 'Kupi vozovnico',
    paymentPageTitle: 'Kupi vozovnico',
    paymentPageDescription: 'Na tej strani boste opravili nakup vozovnice za izbrano relacijo. ',
    travelingElsewhere: 'Potujem drugam',
    line: 'Linija',
    at: 'ob',
    summary: 'Povzetek nakupa',
    adults: 'Odrasli',
    children714: 'Otroci (7-14)',
    children06: 'Otroci (0-6)',
    baggage: 'Prtljaga',
    pay: 'Plačaj',
    totalPrice: 'Skupaj',
    download: 'Prenesi',
    share: 'Deli',
    proceedToPayment: 'Nadaljuj na plačilo',
    youAreHere: 'Tukaj ste.',
  },

};






export const isLanguage = (lang: string): lang is Language => lang in translations;

export const languages = ['en', 'sl'];
export type TranslationKey = keyof typeof translations['en'];