import React, { useState, useCallback } from 'react';
import { Box, type AlertColor, Stack} from '@mui/material';
import {DujppColors} from "../../theme.tsx";
import DButton from "./dbutton.tsx";

// --- QR Code Component Types ---
interface QRCodeProps {
  value: string;
  size?: number;
  level?: 'L' | 'M' | 'Q' | 'H';
  includeMargin?: boolean;
  fgColor?: string;
}

// --- Third-Party Library Mock: QRCode Component ---
const QRCode: React.FC<QRCodeProps> = ({ value, size = 128, fgColor = '#000000' }) => {
  // NOTE: This is a placeholder. A real library like 'qrcode.react' generates the actual QR pattern.
  const placeholderText = "QR Code Placeholder";

  return (
      <svg
          width={size}
          height={size}
          viewBox={`0 0 ${size} ${size}`}
          xmlns="http://www.w3.org/2000/svg"
          role="img"
          aria-labelledby="qr-title"
      >
        <title id="qr-title">QR Code for: {value}</title>
        <rect width={size} height={size} fill="#ffffff" />
        <text
            x="50%"
            y="50%"
            dominantBaseline="middle"
            textAnchor="middle"
            fontSize="10"
            fill={fgColor}
        >
          {placeholderText}
        </text>
      </svg>
  );
};
// -----------------------------------------------------------------------------------

export const MockQrComponent: React.FC = () => {
  // State types
  const [data, setData] = useState<string>('https://www.google.com/search?q=my+ticket+details');
  const [openSnackbar, setOpenSnackbar] = useState<boolean>(false);
  const [snackbarMessage, setSnackbarMessage] = useState<string>('');
  const [snackbarSeverity, setSnackbarSeverity] = useState<AlertColor>('success'); // Using MUI's AlertColor type

  const qrSize: number = 256;

  // Handler for closing the snackbar
  const handleCloseSnackbar = (event?: React.SyntheticEvent | Event, reason?: string) => {
    if (reason === 'clickaway') return;
    setOpenSnackbar(false);
  };

  // Handler for showing the snackbar
  const showSnackbar = (message: string, severity: AlertColor = 'success'): void => {
    setSnackbarMessage(message);
    setSnackbarSeverity(severity);
    setOpenSnackbar(true);
  };

  // 1. Download Functionality
  const handleDownload = useCallback((): void => {
    try {
      // Find the SVG element generated by the QRCode component
      const svgElement = document.getElementById('qr-code-svg') as SVGElement | null;
      if (!svgElement) {
        showSnackbar('QR code element not found.', 'error');
        return;
      }

      const svgData: string = new XMLSerializer().serializeToString(svgElement);
      const canvas: HTMLCanvasElement = document.createElement('canvas');
      const ctx: CanvasRenderingContext2D | null = canvas.getContext('2d');
      const img: HTMLImageElement = new Image();

      if (!ctx) {
        showSnackbar('Canvas context not available.', 'error');
        return;
      }

      img.onload = () => {
        canvas.width = qrSize;
        canvas.height = qrSize;
        ctx.drawImage(img, 0, 0);

        // Convert canvas content to PNG data URL
        const pngFile: string = canvas.toDataURL('image/png');

        // Create a temporary link element for download
        const downloadLink: HTMLAnchorElement = document.createElement('a');
        downloadLink.href = pngFile;
        downloadLink.download = 'qr-code-ticket.png';

        document.body.appendChild(downloadLink);
        downloadLink.click();
        document.body.removeChild(downloadLink);

        showSnackbar('QR code image downloaded!', 'success');
      };

      // Set the SVG as the image source
      img.src = 'data:image/svg+xml;base64,' + btoa(svgData);

    } catch (e) {
      console.error("Download Error:", e);
      showSnackbar('Error during download process.', 'error');
    }
  }, [data]);


  // 2. Share Functionality (Web Share API)
  const handleShare = useCallback(async (): Promise<void> => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My Ticket QR Code',
          text: 'Here is the link for my ticket details.',
          url: data,
        });
        showSnackbar('QR code link shared successfully!', 'success');
      } catch (error) {
        if (error instanceof Error && error.name !== 'AbortError') {
          console.error('Error sharing:', error);
          showSnackbar('Share failed or was cancelled.', 'warning');
        }
      }
    } else {
      // Fallback for browsers that do not support the Web Share API
      showSnackbar('Web Share API is not supported in this browser. Use the download button.', 'warning');
    }
  }, [data]);

  // Memoized QR code component to avoid unnecessary re-renders
  return <Stack>
    <Box id="qr-code-svg">
      <QRCode
          value={data}
          size={qrSize}
          level="H"
          fgColor={DujppColors.primary} // Using the DujppColors object
      />
    </Box>
    <Stack direction={'row'}>
      <DButton label={'Download'} onClick={handleDownload} />
      <DButton label={'Share'} onClick={handleShare} />
    </Stack>
  </Stack>;
}