import React, { useCallback } from 'react';
import { Box, Stack} from '@mui/material';
import {DujppColors} from "../../theme.tsx";
import DButton from "./dbutton.tsx";
import {observer} from "mobx-react-lite";
import {useAppStore} from "../../main.tsx";

// --- QR Code Component Types ---
interface QRCodeProps {
  value: string;
  size?: number;
  level?: 'L' | 'M' | 'Q' | 'H';
  includeMargin?: boolean;
  fgColor?: string;
}

// --- Third-Party Library Mock: QRCode Component ---
const QRCode: React.FC<QRCodeProps> = ({ value, size = 128, fgColor = '#000000' }) => {
  // NOTE: This is a placeholder. A real library like 'qrcode.react' generates the actual QR pattern.
  const placeholderText = "QR Code Placeholder";

  return (
      <svg
          width={size}
          height={size}
          viewBox={`0 0 ${size} ${size}`}
          xmlns="http://www.w3.org/2000/svg"
          role="img"
          aria-labelledby="qr-title"
      >
        <title id="qr-title">QR Code for: {value}</title>
        <rect width={size} height={size} fill="#ffffff" />
        <text
            x="50%"
            y="50%"
            dominantBaseline="middle"
            textAnchor="middle"
            fontSize="10"
            fill={fgColor}
        >
          {placeholderText}
        </text>
      </svg>
  );
};
// -----------------------------------------------------------------------------------

export const MockQrComponent: React.FC = observer(() => {
  // State types
  const data = 'https://www.google.com/search?q=my+ticket+details';

  const qrSize: number = 128;
  const appStore = useAppStore();
  const t = appStore.t;

  // 1. Download Functionality
  const handleDownload = useCallback((): void => {
    try {
      // Find the SVG element generated by the QRCode component
      const svgElement = document.getElementById('qr-code-svg') as SVGElement | null;
      if (!svgElement) {
        return;
      }

      const svgData: string = new XMLSerializer().serializeToString(svgElement);
      const canvas: HTMLCanvasElement = document.createElement('canvas');
      const ctx: CanvasRenderingContext2D | null = canvas.getContext('2d');
      const img: HTMLImageElement = new Image();

      if (!ctx) {
        return;
      }

      img.onload = () => {
        canvas.width = qrSize;
        canvas.height = qrSize;
        ctx.drawImage(img, 0, 0);

        // Convert canvas content to PNG data URL
        const pngFile: string = canvas.toDataURL('image/png');

        // Create a temporary link element for download
        const downloadLink: HTMLAnchorElement = document.createElement('a');
        downloadLink.href = pngFile;
        downloadLink.download = 'qr-code-ticket.png';

        document.body.appendChild(downloadLink);
        downloadLink.click();
        document.body.removeChild(downloadLink);
      };

      // Set the SVG as the image source
      img.src = 'data:image/svg+xml;base64,' + btoa(svgData);

    } catch (e) {
      console.error("Download Error:", e);
    }
  }, [data]);

  return <Stack>
    <Box id="qr-code-svg">
      <QRCode
          value={data}
          size={qrSize}
          level="H"
          fgColor={DujppColors.primary}
      />
    </Box>

      <DButton label={t('download')} onClick={handleDownload} />
  </Stack>;
});